"""Add skills integration tables

Revision ID: skills_001
Revises: f7g8h9i0j1k2
Create Date: 2026-02-04 18:00:00

Tables created:
- portfolio_holdings: User portfolio positions across accounts
- portfolio_snapshots: Point-in-time net worth snapshots
- market_prices: Cached market prices from various sources
- company_profiles: Cached company fundamental data
- skill_outputs: Outputs generated by skills (Excel, PPT, etc.)
- deal_analyses: IB Toolkit deal tracking and history
- skill_memories: Persistent memory for skill learning
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision: str = "skills_001"
down_revision: Union[str, None] = "f7g8h9i0j1k2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create skills integration tables."""

    # =========================================================================
    # PORTFOLIO HOLDINGS
    # =========================================================================
    op.create_table(
        "portfolio_holdings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(50), nullable=False),
        sa.Column("asset_type", sa.String(50), nullable=False),
        sa.Column("asset_name", sa.String(255), nullable=True),
        sa.Column("account_name", sa.String(100), nullable=False),
        sa.Column("account_type", sa.String(50), nullable=False),
        sa.Column("currency", sa.String(10), server_default="CAD"),
        sa.Column("quantity", sa.Float(), nullable=False, server_default="0"),
        sa.Column("cost_basis", sa.Float(), nullable=True),
        sa.Column("cost_per_unit", sa.Float(), nullable=True),
        sa.Column("current_price", sa.Float(), nullable=True),
        sa.Column("current_value", sa.Float(), nullable=True),
        sa.Column("price_updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("metadata", JSONB(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true"),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "symbol", "account_name", name="uq_holding_user_symbol_account"),
    )
    op.create_index("idx_holdings_user_id", "portfolio_holdings", ["user_id"])
    op.create_index("idx_holdings_symbol", "portfolio_holdings", ["symbol"])
    op.create_index("idx_holdings_account", "portfolio_holdings", ["account_name"])
    op.create_index("idx_holdings_asset_type", "portfolio_holdings", ["asset_type"])

    # =========================================================================
    # PORTFOLIO SNAPSHOTS
    # =========================================================================
    op.create_table(
        "portfolio_snapshots",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("snapshot_date", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("total_value", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(10), server_default="CAD"),
        sa.Column("equities_value", sa.Float(), server_default="0"),
        sa.Column("fixed_income_value", sa.Float(), server_default="0"),
        sa.Column("commodities_value", sa.Float(), server_default="0"),
        sa.Column("crypto_value", sa.Float(), server_default="0"),
        sa.Column("cash_value", sa.Float(), server_default="0"),
        sa.Column("real_estate_value", sa.Float(), server_default="0"),
        sa.Column("other_value", sa.Float(), server_default="0"),
        sa.Column("liabilities_value", sa.Float(), server_default="0"),
        sa.Column("breakdown", JSONB(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_snapshots_user_date", "portfolio_snapshots", ["user_id", "snapshot_date"])

    # =========================================================================
    # MARKET PRICES
    # =========================================================================
    op.create_table(
        "market_prices",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(50), nullable=False),
        sa.Column("source", sa.String(50), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(10), server_default="USD"),
        sa.Column("change_1d", sa.Float(), nullable=True),
        sa.Column("change_1w", sa.Float(), nullable=True),
        sa.Column("change_1m", sa.Float(), nullable=True),
        sa.Column("change_1y", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("market_cap", sa.Float(), nullable=True),
        sa.Column("metadata", JSONB(), nullable=True),
        sa.Column("price_timestamp", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "source", name="uq_price_symbol_source"),
    )
    op.create_index("idx_prices_symbol", "market_prices", ["symbol"])
    op.create_index("idx_prices_symbol_source", "market_prices", ["symbol", "source"])
    op.create_index("idx_prices_timestamp", "market_prices", ["price_timestamp"])

    # =========================================================================
    # COMPANY PROFILES
    # =========================================================================
    op.create_table(
        "company_profiles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(50), nullable=False, unique=True),
        sa.Column("name", sa.String(255), nullable=True),
        sa.Column("sector", sa.String(100), nullable=True),
        sa.Column("industry", sa.String(100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("website", sa.String(255), nullable=True),
        sa.Column("country", sa.String(100), nullable=True),
        sa.Column("exchange", sa.String(50), nullable=True),
        sa.Column("market_cap", sa.Float(), nullable=True),
        sa.Column("enterprise_value", sa.Float(), nullable=True),
        sa.Column("revenue_ttm", sa.Float(), nullable=True),
        sa.Column("ebitda_ttm", sa.Float(), nullable=True),
        sa.Column("net_income_ttm", sa.Float(), nullable=True),
        sa.Column("pe_ratio", sa.Float(), nullable=True),
        sa.Column("ev_ebitda", sa.Float(), nullable=True),
        sa.Column("ev_revenue", sa.Float(), nullable=True),
        sa.Column("price_to_book", sa.Float(), nullable=True),
        sa.Column("revenue_growth", sa.Float(), nullable=True),
        sa.Column("earnings_growth", sa.Float(), nullable=True),
        sa.Column("raw_data", JSONB(), nullable=True),
        sa.Column("data_source", sa.String(50), server_default="yahoo_finance"),
        sa.Column("data_as_of", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_company_symbol", "company_profiles", ["symbol"])
    op.create_index("idx_company_sector", "company_profiles", ["sector"])

    # =========================================================================
    # SKILL OUTPUTS
    # =========================================================================
    op.create_table(
        "skill_outputs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("skill_name", sa.String(100), nullable=False),
        sa.Column("module_name", sa.String(100), nullable=True),
        sa.Column("output_type", sa.String(50), nullable=False),
        sa.Column("file_name", sa.String(255), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("storage_path", sa.String(500), nullable=True),
        sa.Column("storage_url", sa.String(500), nullable=True),
        sa.Column("local_path", sa.String(500), nullable=True),
        sa.Column("input_parameters", JSONB(), nullable=True),
        sa.Column("company_symbol", sa.String(50), nullable=True),
        sa.Column("status", sa.String(50), server_default="completed"),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("metadata", JSONB(), nullable=True),
        sa.Column("tags", JSONB(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_outputs_user_id", "skill_outputs", ["user_id"])
    op.create_index("idx_outputs_skill", "skill_outputs", ["skill_name"])
    op.create_index("idx_outputs_company", "skill_outputs", ["company_symbol"])
    op.create_index("idx_outputs_created", "skill_outputs", ["created_at"])

    # =========================================================================
    # DEAL ANALYSES
    # =========================================================================
    op.create_table(
        "deal_analyses",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("deal_name", sa.String(255), nullable=False),
        sa.Column("company_symbol", sa.String(50), nullable=True),
        sa.Column("company_name", sa.String(255), nullable=True),
        sa.Column("deal_type", sa.String(50), nullable=True),
        sa.Column("status", sa.String(50), server_default="in_progress"),
        sa.Column("enterprise_value", sa.Float(), nullable=True),
        sa.Column("entry_multiple", sa.Float(), nullable=True),
        sa.Column("exit_multiple", sa.Float(), nullable=True),
        sa.Column("target_irr", sa.Float(), nullable=True),
        sa.Column("target_moic", sa.Float(), nullable=True),
        sa.Column("current_phase", sa.Integer(), server_default="0"),
        sa.Column("completed_prompts", JSONB(), nullable=True),
        sa.Column("state_data", JSONB(), nullable=True),
        sa.Column("outputs", JSONB(), nullable=True),
        sa.Column("investment_thesis", sa.Text(), nullable=True),
        sa.Column("key_risks", JSONB(), nullable=True),
        sa.Column("recommendation", sa.String(50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_deals_user_id", "deal_analyses", ["user_id"])
    op.create_index("idx_deals_company", "deal_analyses", ["company_symbol"])
    op.create_index("idx_deals_status", "deal_analyses", ["status"])

    # =========================================================================
    # SKILL MEMORIES
    # =========================================================================
    op.create_table(
        "skill_memories",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("skill_name", sa.String(100), nullable=False),
        sa.Column("memory_type", sa.String(50), nullable=False),
        sa.Column("memory_key", sa.String(255), nullable=False),
        sa.Column("content", JSONB(), nullable=False),
        sa.Column("access_count", sa.Integer(), server_default="0"),
        sa.Column("last_accessed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("relevance_score", sa.Float(), server_default="1.0"),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "skill_name", "memory_type", "memory_key", name="uq_memory_key"),
    )
    op.create_index("idx_memory_user_skill", "skill_memories", ["user_id", "skill_name"])
    op.create_index("idx_memory_type", "skill_memories", ["memory_type"])


def downgrade() -> None:
    """Drop skills integration tables."""
    op.drop_table("skill_memories")
    op.drop_table("deal_analyses")
    op.drop_table("skill_outputs")
    op.drop_table("company_profiles")
    op.drop_table("market_prices")
    op.drop_table("portfolio_snapshots")
    op.drop_table("portfolio_holdings")
